version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todopassword

  redis:
    image: "redis:latest"
    ports:
      - "6370:6379"

  daphne:
    build: .
    command: sh -c "python manage.py makemigrations --merge --no-input&&python manage.py makemigrations --no-input&&python manage.py migrate&&daphne -b 0.0.0.0 -p 8000 secure_to_do.asgi:application"
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    ports:
      - 8000:8000


