# Generated by Django 3.2.8 on 2023-12-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0002_alter_plan_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='fetch_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='fetch_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['plan_name', 'owner'], name='to_do_app_p_plan_na_576f78_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['created_at', 'modified_at'], name='to_do_app_p_created_28a892_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['plan', 'task_name'], name='to_do_app_t_plan_id_23f93a_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_at', 'modified_at'], name='to_do_app_t_created_014aa4_idx'),
        ),
    ]
